stages:
  - build

windows:
  stage: build
  script: "buildscripts/build.bat"
  artifacts:
    when: always
    paths:
      - builds/bin/
    expire_in: 60 mins
  tags:
    - windows
    - vs2015
    - EU
