#ifndef llshost_opcodes_h__
#define llshost_opcodes_h__

enum
{
  LLS_OP_EXIT = 0,

  LLS_OP_MOV_IMM_REGISTER,
  LLS_OP_MOV_REGISTER_REGISTER,
  LLS_OP_MOV_REGISTER_STACK,
  LLS_OP_MOV_STACK_REGISTER,
  LLS_OP_MOV_STACK_STACK,
  LLS_OP_MOV_REGISTER__PTR_IN_REGISTER,
  LLS_OP_MOV_PTR_IN_REGISTER__REGISTER,

  LLS_OP_MOV_REGISTER_STACK_N_BYTES,
  LLS_OP_MOV_STACK_STACK_N_BYTES,
  LLS_OP_MOV_REGISTER__PTR_IN_REGISTER_N_BYTES,

  LLS_OP_LEA_STACK_TO_REGISTER,

  LLS_OP_PUSH_REGISTER,
  LLS_OP_POP_REGISTER,

  LLS_OP_STACK_INC_IMM,
  LLS_OP_STACK_INC_REGISTER,
  LLS_OP_STACK_DEC_IMM,
  LLS_OP_STACK_DEC_REGISTER,

  LLS_OP_ADD_IMM,
  LLS_OP_ADD_REGISTER,
  LLS_OP_MULI_IMM,
  LLS_OP_MULI_REGISTER,
  LLS_OP_DIVI_IMM,
  LLS_OP_DIVI_REGISTER,
  LLS_OP_MULU_IMM,
  LLS_OP_MULU_REGISTER,
  LLS_OP_DIVU_IMM,
  LLS_OP_DIVU_REGISTER,
  LLS_OP_MOD_IMM,
  LLS_OP_MOD_REGISTER,

  LLS_OP_BSL_REGISTER,
  LLS_OP_BSR_REGISTER,
  LLS_OP_AND_REGISTER,
  LLS_OP_AND_IMM,
  LLS_OP_OR_REGISTER,
  LLS_OP_XOR_REGISTER,

  LLS_OP_LOGICAL_AND_REGISTER,
  LLS_OP_LOGICAL_OR_REGISTER,

  LLS_OP_INV_REGISTER,
  LLS_OP_NOT_REGISTER,

  LLS_OP_EQ_REGISTER,
  LLS_OP_LT_REGISTER,
  LLS_OP_GT_REGISTER,

  LLS_OP_NEGATE_REGISTER,

  LLS_OP_CMP_NEQ_IMM_REGISTER,

  LLS_OP_JMP,
  LLS_OP_JMP_RELATIVE_IMM,
  LLS_OP_JMP_RELATIVE_REGISTER,

  LLS_OP_JUMP_CMP_TRUE,
  LLS_OP_JUMP_CMP_TRUE_RELATIVE_IMM,
  LLS_OP_JUMP_CMP_TRUE_RELATIVE_REGISTER,

  LLS_OP_CALL_INTERNAL_RELATIVE_IMM,
  LLS_OP_CALL_INTERNAL_RELATIVE_REGISTER,
  LLS_OP_RETURN_INTERNAL,

  LLS_OP_CALL_EXTERNAL__RESULT_TO_REGISTER,

  LLS_OP_CALL_BUILTIN__RESULT_TO_REGISTER__ID_FROM_REGISTER,
  
  LLS_OP_MOV_RUNTIME_PARAM_REGISTER,
};

#endif // llshost_opcodes_h__
