#ifndef llshost_opcodes_h__
#define llshost_opcodes_h__

enum
{
  LLS_OP_EXIT = 0,

  LLS_OP_MOV_IMM_REGISTER,
  LLS_OP_MOV_REGISTER_REGISTER,
  LLS_OP_MOV_REGISTER_STACK,
  LLS_OP_MOV_STACK_REGISTER,
  LLS_OP_MOV_STACK_STACK,
  LLS_OP_MOV_REGISTER__PTR_IN_REGISTER,
  LLS_OP_MOV_PTR_IN_REGISTER__REGISTER,

  LLS_OP_MOV_REGISTER_STACK_N_BYTES,
  LLS_OP_MOV_REGISTER__PTR_IN_REGISTER_N_BYTES,

  LLS_OP_LEA_STACK_TO_REGISTER,

  LLS_OP_PUSH_REGISTER,
  LLS_OP_POP_REGISTER,

  LLS_OP_STACK_INC_IMM,
  LLS_OP_STACK_INC_REGISTER,
  LLS_OP_STACK_DEC_IMM,
  LLS_OP_STACK_DEC_REGISTER,

  LLS_OP_UADD_IMM,
  LLS_OP_UADD_REGISTER,
  LLS_OP_USUB_IMM,
  LLS_OP_USUB_REGISTER,
  LLS_OP_UMUL_IMM,
  LLS_OP_UMUL_REGISTER,
  LLS_OP_UDIV_IMM,
  LLS_OP_UDIV_REGISTER,
  LLS_OP_UMOD_IMM,
  LLS_OP_UMOD_REGISTER,

  LLS_OP_ADD_IMM,
  LLS_OP_ADD_REGISTER,
  LLS_OP_SUB_IMM,
  LLS_OP_SUB_REGISTER,
  LLS_OP_MUL_IMM,
  LLS_OP_MUL_REGISTER,
  LLS_OP_DIV_IMM,
  LLS_OP_DIV_REGISTER,
  LLS_OP_MOD_IMM,
  LLS_OP_MOD_REGISTER,

  LLS_OP_BSL_REGISTER,
  LLS_OP_BSR_REGISTER,
  LLS_OP_AND_REGISTER,
  LLS_OP_OR_REGISTER,
  LLS_OP_XOR_REGISTER,

  LLS_OP_LOGICAL_AND_REGISTER,
  LLS_OP_LOGICAL_OR_REGISTER,

  LLS_OP_INV,
  LLS_OP_NOT,

  LLS_OP_INEGATE,
  LLS_OP_FNEGATE,

  LLS_OP_CMP_EQ_IMM,
  LLS_OP_CMP_GT_IMM,
  LLS_OP_CMP_LT_IMM,

  LLS_OP_CMP_EQ_REGISTER,
  LLS_OP_CMP_GT_REGISTER,
  LLS_OP_CMP_LT_REGISTER,

  LLS_OP_JMP,
  LLS_OP_JMP_RELATIVE_IMM,
  LLS_OP_JMP_RELATIVE_REGISTER,

  LLS_OP_JUMP_CMP_TRUE,
  LLS_OP_JUMP_CMP_TRUE_RELATIVE_IMM,
  LLS_OP_JUMP_CMP_TRUE_RELATIVE_REGISTER,

  LLS_OP_CALL_INTERNAL_IMM,
  LLS_OP_CALL_INTERNAL_REGISTER,
  LLS_OP_RETURN_INTERNAL,

  LLS_OP_CALL_EXTERNAL__RESULT_TO_REGISTER,

  LLS_OP_CALL_BUILTIN__RESULT_TO_REGISTER__ID_FROM_REGISTER,
};

#endif // llshost_opcodes_h__
